import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Header } from "@/components/Header";
import { ReactNode } from "react";
import "./globals.css";
import { AuthContextProvider } from "@/store/Auth";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Cine Stats",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <AuthContextProvider>
                    <Header />
                    {children}
                </AuthContextProvider>
            </body>
        </html>
    );
}
